"""empty message

Revision ID: 4471009d1901
Revises: f1b24a973c63
Create Date: 2023-08-15 21:36:26.612019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4471009d1901'
down_revision = 'f1b24a973c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('status_name_key', 'status', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('status_name_key', 'status', ['name'])
    # ### end Alembic commands ###
