"""empty message

Revision ID: 49886963536d
Revises: 
Create Date: 2022-07-29 14:01:49.003405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
from app.models import db

# revision identifiers, used by Alembic.
revision = '49886963536d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    db.engine.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.create_table('clusters',
                    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text(
                        'uuid_generate_v4()'), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('host', sa.String(), nullable=False),
                    sa.Column('token', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(
                    ), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('prometheus_url', sa.String(), nullable=True),
                    sa.Column('cost_modal_url', sa.String(), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('host'),
                    sa.UniqueConstraint('name')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clusters')
    # ### end Alembic commands ###
