replicaCount: 2

image:
  repository: gcr.io/crane-cloud-274413/cranecloud-status-backend
  pullPolicy: Always
  tag: ${{ DOCKER_IMAGE_TAG }}

imagePullSecrets: []

nameOverride: "cranecloud-status-backend"
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 80

resources: {}
  # limits:
  #   cpu: 512m
  #   memory: 512Mi
  # requests:
  #   cpu: 512m
  #   memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

nginxConf:
  server {
        listen 80;

        location / {
            proxy_pass http://localhost:5000/;
        }
    }

environment:
  ADMIN_MYSQL_HOST: 196.43.134.154
  ADMIN_MYSQL_PASSWORD: ${{ MYSQL_PASSWORD }}
  ADMIN_MYSQL_PORT: 32765
  ADMIN_MYSQL_USER: crane
  ADMIN_PSQL_HOST: 196.43.134.154
  ADMIN_PSQL_PASSWORD: ${{ PSQL_PASSWORD }}
  ADMIN_PSQL_PORT: 32763
  ADMIN_PSQL_USER: crane
  BACKEND_BASE_URL: http://staging-api.cranecloud.io
  CLIENT_BASE_URL: https://staging.cranecloud.io
  DATABASE_URI: ${{ DATABASE_URL }}
  FLASK_APP: server.py
  FLASK_APP_SALT: ${{ APP_SALT }}
  FLASK_APP_SECRET: ${{ APP_SECRET }}
  FLASK_ENV: production
  MIRA_BACKEND_URL: https://mira.cranecloud.io
  MIRA_FRONTEND_URL: https://mira.cranecloud.io
  PROMETHEUS_URL: http://staging-prom.cranecloud.io/
  REGISTRY_URL: http://registry.cranecloud.io
  REDIS_URL: ${{ REDIS_URL }}
